### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by reisir** [MiaSize/Rainmeter#1]
Hi I would appreciate if you would uhh delete this. You probably got the old version of [Skycoder](https://github.com/reisir/skycoder) from visualskins and modified it. 

The new version of Skycoder has size and color options and if you worked off of the version visualskins offers, you were working on an already unauthorized and modified version of my code.

Anyway, if you have stuff you want to add to Skycoder, I'm open for contributions. I just don't want duplicate copies of my skin floating around the internet, not on visualskins and not on github

**Comment by MiaSize** [comment]
ummm so what I'm hearing is this is your old code and you'd just be happy if I hadn't modified it?

**Comment by MiaSize** [comment]
Can I credit you? I think you're idea is super cool I just wanted to edit it and since it was out on the internet that's all I did I in no way was trying to take credit for everything I only modified it.

**Comment by reisir** [comment]
I'm not saying I would be happy if you hadn't modified it. I would be happy if visualskins didn't take my skin in the first place. I'm asking you to remove this repository, and pointing you towards making a pull request to reisir/skycoder if you have features you'd like to add to it. Although if the only feature you want is launching overwatch, I will not add it. Skycoder already has color options, so I don't know what your version offers.

Currently, this repository contains an inferior version of Skycoder (compared to the latest version) and visualskins contains an even worse version. Both you and visualskins.com are distributing my code. I won't be pursuing any copyright / legal action, just letting you know that I would like it if you would stop distributing my code. It just confuses people, it'd be better if they got the actual latest version from the original source.

**Comment by MiaSize** [comment]
@reisir 
I understand it is wrong; others have previously taken old versions of your code and distributed it under their name. If you would have read my README document you'd notice the fourth line tells the audience that I in no way created this code, I modified it, and I gave create to those who I believed were the creators at the time. 

I have now updated my README doc to specify you as the creator of Skycoder along with Nighthawk. You had a good idea when making Skycoder, although I had my own ideas to customize to my needs. If you read further into my README you'd notice I did not only change the widget to use a shortcut to launch overwatch. I also do not appreciate that you discredited the modifications I made by calling it "inferior" to your latest version of Skycoder. As your GitHub freely gives the source code to the "latest original source" of Skycoder I see no reason to take down my repository as it is free open-source code on a coding collaboration platform. 

I perceive this older "inferior" version of Skycoder to be still better than your latest version. I also find it unfair that you claimed to have created Skycoder alone but you credit Nighthawk for the design in your GitHub. However, this design in general is also not original because it references the character design of Sombra from Overwatch. 

Therefore, I will not be removing my work from GitHub, and hope you can come to understand that this is not an offense to you or your work. GitHub is a place for collaboration and feedback and you've already rejected my version of better based on bias.
